# Running diagnostics for dummy run

In [1]:
from sage.plotting import ValidationPlotManager

In [2]:
plotter = ValidationPlotManager(
    validation_h5="./run_export/validation_data.h5", 
    losses_h5="./run_export/losses.h5", 
    export_dir="./run_export"
)

In [3]:
plotter.make_all_plots(save=True)

In [13]:
import h5py

print('Training')
with h5py.File("./run_export/losses.h5") as fp:
    print(fp['training']['loss'][:10])

print('\nValidation')
with h5py.File("./run_export/losses.h5") as fp:
    print(fp['validation']['loss'][:10])

Training
[[ 0.23843737  0.24158041 -0.87331355  0.24474558]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]

Validation
[[ 0.18978788  0.19672276 -1.574388    0.18743956]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.    

In [6]:
with h5py.File("./run_export/validation_data.h5") as fp:
    data = fp['epoch_0000/network_output'][:]

In [7]:
import numpy as np
data = np.vstack(data)

In [12]:
data[data[:,0]<5][:15]

array([[ 0.03189087, 11.074687  , 23.08695   ,  0.36157227,  0.6713867 ],
       [-0.60546875, 11.080102  , 22.047388  ,  0.45483398,  0.6699219 ],
       [ 1.8085938 , 11.186263  , 26.963436  ,  0.23291016,  0.65527344],
       [-4.4257812 , 11.102942  , 18.391207  ,  0.31274414,  0.3059082 ],
       [ 1.2314453 , 11.16844   , 25.028217  ,  0.2614746 ,  0.6586914 ],
       [-4.7265625 , 11.099586  , 18.383308  ,  0.29760742,  0.2854004 ],
       [-3.6347656 , 11.094505  , 18.928328  ,  0.34521484,  0.36645508],
       [-1.7089844 , 11.125758  , 19.95518   ,  0.36914062,  0.49365234],
       [-4.3359375 , 11.100312  , 18.596577  ,  0.3125    ,  0.30249023],
       [-3.03125   , 11.08792   , 19.311422  ,  0.37451172,  0.43188477],
       [-0.22766113, 11.122163  , 21.175552  ,  0.42456055,  0.6660156 ],
       [-2.7128906 , 11.085177  , 19.60763   ,  0.40844727,  0.46972656],
       [-1.2714844 , 11.054594  , 17.913326  ,  0.38891602,  0.49389648],
       [-2.4121094 , 11.099027  , 18.3

In [11]:
data[data[:,0]>11][:15]

array([[11.0078125 , 11.03522   , 26.234766  ,  0.06530762,  0.4975586 ],
       [11.109375  , 11.189873  , 20.219791  ,  0.07958984,  0.2902832 ],
       [11.2890625 , 11.040184  , 24.691528  ,  0.06414795,  0.46289062],
       [11.2734375 , 11.027155  , 17.782993  ,  0.09429932,  0.30078125],
       [11.0703125 , 11.142862  , 18.49389   ,  0.065979  ,  0.29492188],
       [12.3828125 , 11.110488  , 24.57897   ,  0.05166626,  0.359375  ],
       [11.109375  , 11.111214  , 29.263977  ,  0.05935669,  0.46923828],
       [11.0703125 , 11.041425  , 25.135838  ,  0.06842041,  0.42138672],
       [11.1328125 , 11.003467  , 25.780582  ,  0.06671143,  0.5058594 ],
       [11.109375  , 11.110368  , 33.63994   ,  0.07678223,  0.43603516],
       [11.6328125 , 11.15998   , 25.510046  ,  0.06304932,  0.38183594],
       [11.53125   , 11.159698  , 18.722958  ,  0.0736084 ,  0.2619629 ],
       [11.1171875 , 11.117171  , 28.039654  ,  0.06030273,  0.41064453],
       [11.7734375 , 11.119216  , 32.3