# Running diagnostics for dummy run

In [1]:
from sage.plotting import ValidationPlotManager

In [2]:
plotter = ValidationPlotManager(
    validation_h5="./run_export/validation_data.h5", 
    losses_h5="./run_export/losses.h5", 
    export_dir="./run_export"
)

In [3]:
plotter.make_all_plots(save=True)

In [4]:
import h5py

print('Training')
with h5py.File("./run_export/losses.h5") as fp:
    print(fp['training']['loss'][:])

print('\nValidation')
with h5py.File("./run_export/losses.h5") as fp:
    print(fp['validation']['loss'][:])

Training
[[ 0.24298654  0.23181298  1.0601454   1.1747956 ]
 [ 0.18757302  0.18132019  0.3101613   0.9402698 ]
 [ 0.17270663  0.16774544  0.09827559  0.89395285]
 [ 0.16927654  0.16466348  0.0459131   0.8767532 ]
 [ 0.15606989  0.15269014 -0.16062775  0.8366171 ]]

Validation
[[ 0.21157718  0.20507097  0.39587364  0.90526277]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.1566576   0.15383801 -0.2549986   0.8188846 ]]


In [12]:
with h5py.File("./run_export/validation_data.h5") as fp:
    data = fp['epoch_0004/network_output'][:]

In [16]:
import numpy as np
data = np.vstack(data)

In [24]:
data[data[:,0]>11][:5]

array([[11.78   , -1.584  , 14.836  , -5.71   ,  0.489  ],
       [11.195  ,  1.219  , 16.52   , -5.316  ,  0.628  ],
       [11.875  , -1.148  , 14.03   , -5.543  ,  0.2185 ],
       [11.59   , -1.135  , 23.36   , -6.934  ,  1.573  ],
       [12.02   ,  0.0399 , 13.516  , -5.44   , -0.03232]], dtype=float16)