# Running diagnostics for dummy run

In [1]:
from sage.plotting import ValidationPlotManager

import matplotlib.pyplot as plt
import numpy as np
import h5py

In [2]:
plotter = ValidationPlotManager(
    validation_h5="./run_export/validation_data.h5", 
    losses_h5="./run_export/losses.h5", 
    export_dir="./run_export"
)

In [3]:
plotter.make_all_plots(save=True)

In [8]:
print('Training')
with h5py.File("./run_export/losses.h5") as fp:
    print(fp['training']['loss'][:])

print('\nValidation')
with h5py.File("./run_export/losses.h5") as fp:
    print(fp['validation']['loss'][:])

Training
[[ 0.23843737  0.24158041 -0.87331355  0.24474558]
 [ 0.17587593  0.18301369 -1.6113821   0.18393783]
 [ 0.1604817   0.16881666 -1.8378758   0.1707493 ]
 [ 0.1586543   0.16721526 -1.8799714   0.16775239]
 [ 0.1446285   0.15437736 -2.1062376   0.15638523]
 [ 0.15076372  0.1599632  -2.0005496   0.16081087]
 [ 0.14967196  0.15903676 -2.0311852   0.15829554]
 [ 0.14356758  0.15352654 -2.1447818   0.1530237 ]
 [ 0.13653614  0.14702071 -2.2452538   0.14841168]
 [ 0.13259853  0.14350042 -2.3250268   0.14461929]
 [ 0.13847238  0.14893115 -2.2397666   0.14798078]
 [ 0.14353573  0.15347244 -2.1393452   0.1520723 ]
 [ 0.14189631  0.15207699 -2.1858482   0.149748  ]
 [ 0.13928142  0.14973453 -2.2380595   0.14737886]
 [ 0.13593464  0.14664382 -2.2868855   0.14500387]
 [ 0.13376695  0.14470494 -2.3302674   0.14269587]
 [ 0.13076769  0.14196222 -2.379771    0.14083886]
 [ 0.1287058   0.14011112 -2.4201243   0.1391118 ]
 [ 0.1272279   0.13879317 -2.4507847   0.13771003]
 [ 0.12586486  0.13755

In [2]:
epoch = "0079"

with h5py.File("./run_export/validation_data.h5") as fp:
    print(fp['epoch_0000'].keys())
    data = fp[f'epoch_{epoch}/network_output'][:]
    params = fp[f'epoch_{epoch}/signal_params'][:]
    target = fp[f'epoch_{epoch}/network_target'][:]

<KeysViewHDF5 ['network_output', 'network_target', 'signal_params']>


In [7]:
data

array([[-2.        , 11.138463  , 19.003366  ,  0.23864746,  0.23632812],
       [-2.7695312 , 11.120739  , 13.284598  ,  0.28759766,  0.18127441],
       [ 7.8242188 , 11.125702  , 22.722246  ,  0.16821289,  0.32788086],
       ...,
       [-3.1503906 , 11.087519  , 15.342249  ,  0.21484375,  0.20654297],
       [-0.28295898, 11.045344  , 14.848571  ,  0.65234375,  0.32788086],
       [12.625     , 11.112412  , 24.293623  ,  0.03515625,  0.33789062]],
      shape=(199936, 5), dtype=float32)

In [9]:
signal_idxs = np.argwhere(target[:,-1] == 1.0).flatten()

In [10]:
data[signal_idxs]

array([[ 7.82421875e+00,  1.11257019e+01,  2.27222462e+01,
         1.68212891e-01,  3.27880859e-01],
       [ 1.18750000e+01,  1.11316099e+01,  3.10886116e+01,
         2.72216797e-02,  3.42285156e-01],
       [ 1.28203125e+01,  1.11971483e+01,  3.73839951e+01,
         2.40783691e-02,  3.26660156e-01],
       ...,
       [ 7.64453125e+00,  1.10481081e+01,  1.70918446e+01,
         1.04797363e-01,  2.45971680e-01],
       [-2.82958984e-01,  1.10453444e+01,  1.48485708e+01,
         6.52343750e-01,  3.27880859e-01],
       [ 1.26250000e+01,  1.11124125e+01,  2.42936230e+01,
         3.51562500e-02,  3.37890625e-01]],
      shape=(99968, 5), dtype=float32)

In [11]:
signal_idxs

array([     2,      4,      5, ..., 199930, 199934, 199935],
      shape=(99968,))

In [17]:
data.shape, params.shape

((199936, 5), (99968, 25))

In [20]:
np.random.choice(np.arange(1, 13), size=12, replace=False)

array([ 6,  2,  7,  4, 11,  1,  9, 12,  5,  8,  3, 10])

In [15]:
data = np.vstack(data)
params = np.vstack(params)

In [ ]:
plt.scatter(data[:,1], params[:,-1])